@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class VersionedAddressBook
Class ModelManager
Class UserPrefs

Class UniqueOpportunityList
Class Opportunity
Class Name
Class Email
Class ContactRole
Class Company
Class Role
Class Status
Class Cycle
Class Phone
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
VersionedAddressBook -up-|> AddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" VersionedAddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueOpportunityList
UniqueOpportunityList --> "~* all" Opportunity
Opportunity *--> "1" Name
Opportunity *--> "1" Email
Opportunity *--> "1" ContactRole
Opportunity *--> "1" Company
Opportunity *--> "1" Role
Opportunity *--> "1" Status
Opportunity *--> "1" Cycle
Opportunity *--> "0..1" Phone
VersionedAddressBook *--> "1..*" ReadOnlyAddressBook

Name -[hidden]right-> Email
Email -[hidden]right-> ContactRole
ContactRole -[hidden]right-> Company
Company -[hidden]right-> Role
Role -[hidden]right-> Status
Status -[hidden]right-> Cycle
Cycle -[hidden]right-> Phone

ModelManager --> "~* filtered" Opportunity
@enduml
